[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ovos-gguf-plugin"
dynamic = ["version"]
description = "local LLM plugin for OpenVoiceOS persona framework"
readme = "README.md"
license = "MIT"
authors = [{name = "jarbasai", email = "jarbasai@mailfence.com"}]
requires-python = ">=3.9"
keywords = [
    "OVOS",
    "openvoiceos",
    "plugin",
    "utterance",
    "fallback",
    "query",
]
dependencies = [
    "ovos-plugin-manager>=2.2.3a1,<3.0.0",
    "huggingface-hub",
    "llama-cpp-python",
    "sentence_stream",
]

[project.urls]
Homepage = "https://github.com/TigreGotico/ovos-gguf-plugin"
Repository = "https://github.com/TigreGotico/ovos-gguf-plugin"

[project.entry-points."opm.transformer.dialog"]
ovos-dialog-transformer-gguf-plugin = "ovos_gguf_plugin.dialog_transformers:GGUFDialogTransformer"

[project.entry-points."opm.agents.chat"]
ovos-chat-gguf-plugin = "ovos_gguf_plugin.chat:GGUFChatEngine"

[project.entry-points."opm.agents.summarizer"]
ovos-summarizer-gguf-plugin = "ovos_gguf_plugin.summarizer:GGUFSummarizer"

[project.entry-points."opm.lang.translate"]
ovos-translate-gguf-plugin = "ovos_gguf_plugin.translate:GGUFTextTranslator"

[project.entry-points."opm.lang.detect"]
ovos-lang-detect-gguf-plugin = "ovos_gguf_plugin.translate:GGUFTextLangDetector"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["ovos_gguf_plugin*"]

[tool.setuptools.dynamic]
version = {attr = "ovos_gguf_plugin.version.__version__"}
